### PR TITLE
Scraper for Medium articles, modified the name of the pre-commit file

### PR DESCRIPTION
**Pull request by Saurav-Shrivastav**
- Scrapes articles from Medium.com
- The scraping is done on the basis of a tag or search criteria that is fed by the user

### CODE REVIEW

**Comment by shubhank-saxena** [comment]
@Saurav-Shrivastav PR complete?

**Comment by Saurav-Shrivastav** [comment]
Yes, I did the changes that you had suggested!

**Comment by shubhank-saxena** [comment]
@Saurav-Shrivastav this is looking good! Just rename your folder to Medium instead of Slackbot-Scraping

**Comment by shubhank-saxena** [comment]
What happened?

**Pull request closed without merging**
